volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: lkofe1/kittygram_backend:latest
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: lkofe1/kittygram_frontend:latest
    env_file: .env
    volumes:
      - static:/static

  gateway:
    image: lkofe1/kittygram_gateway:latest
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - static:/static/
      - media:/media/
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend

  taski_backend:
    image: ${{ secrets.DOCKER_USERNAME }}/taski_backend:latest
    env_file: .env
    volumes:
      - taski_static:/app/static/
    depends_on:
      - db

  taski_frontend:
    image: ${{ secrets.DOCKER_USERNAME }}/taski_frontend:latest


 volumes:
   taski_static:
