volumes:
  pg_data:
  static:
  media:
  taski_static:

services:
  db:
    image: postgres:13
    restart: always
    env_file: .env
    volumes:
      - pg_data:/var/lib/postgresql/data

  backend:
    image: lkofe1/kittygram_backend:latest
    restart: always
    env_file: .env
    volumes:
      - static:/app/static/
      - media:/app/media/
    depends_on:
      - db

  frontend:
    image: lkofe1/kittygram_frontend:latest
    restart: always
    env_file: .env
    volumes:
      - static:/static

  taski_backend:
    image: lkofe1/taski_backend:latest
    restart: always
    env_file: .env
    volumes:
      - taski_static:/app/static/
    depends_on:
      - db

  taski_frontend:
    image: lkofe1/taski_frontend:latest
    restart: always
    volumes:
      - taski_static:/app/build/

  gateway:
    image: lkofe1/kittygram_gateway:latest
    restart: always
    env_file: .env
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - static:/static/
      - media:/media/
      - taski_static:/var/www/taski/
      - /var/www/certbot:/var/www/certbot
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
      - frontend
      - taski_backend
