server {
    listen 80;
    server_name kittygram12.ydns.eu;
    server_tokens off;

    client_max_body_size 20M;

    location /.well-known/acme-challenge/ {
        root /var/www/certbot;
    }

    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name kittygram12.ydns.eu;
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/kittygram12.ydns.eu-0001/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kittygram12.ydns.eu-0001/privkey.pem;

    location /api/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000;
    }

    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_pass http://backend:8000;
    }

    location /media/ {
        alias /media/;
    }

    location /static/ {
        alias /static/;
    }

    location / {
        root /static/;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name taski.ydns.eu;
    server_tokens off;
    location / { return 301 https://$host$request_uri; }
}

server {
    listen 443 ssl;
    server_name taski.ydns.eu;
    server_tokens off;

    ssl_certificate /etc/letsencrypt/live/taski.ydns.eu/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/taski.ydns.eu/privkey.pem;

    location /api/ {
        proxy_set_header Host $http_host;
        proxy_pass http://taski_backend:8000; 
    }
    
    location /admin/ {
        proxy_set_header Host $http_host;
        proxy_pass http://taski_backend:8000;
    }

    location /static/admin/ {
        alias /var/www/taski/admin/;
    }

    location /static/rest_framework/ {
        alias /var/www/taski/rest_framework/;
    }

    location /static/ {
        root /var/www/taski/;
    }

    location / {
        root /var/www/taski/;
        index index.html index.htm;
        try_files $uri $uri/ /index.html =404;
    }
}
